---
# tasks file for ansible-role-dotfiles

- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: "Ensure all files are in place."
  synchronize:
    src: "{{ dotfiles_repo_local_destination }}/"
    dest: "{{ dotfiles_home }}/"
  become: false
