---
# tasks file for ansible-role-dotfiles

- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: "Ensure {{ dotfiles_vim_colors_full_path }} directory is present."
  file:
    path: "{{ dotfiles_vim_colors_full_path | dirname }}"
    state: directory
    mode: "0775"
  become: false

- name: "Ensure vim themes are present."
  copy:
    src: "{{ item }}"
    dest: "{{ dotfiles_vim_colors_full_path }}/"
    mode: "0644"
  become: false
  with_fileglob:
    - "{{ dotfiles_repo_local_destination }}/{{ dotfiles_vim_colors_path }}/*"

- name: "Ensure dotfiles are in their location."
  copy:
    src: "{{ item }}"
    dest: "{{ dotfiles_home }}/"
    mode: "0644"
  become: false
  with_fileglob:
    - "{{ dotfiles_repo_local_destination }}/.*"
